<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>DotProlog.Compiler</RootNamespace>

        <IsPackable>true</IsPackable>
        <PackageId>DotProlog.Compiler</PackageId>
        <Title>DotProlog compiler and engine</Title>
        <Description>Compiles Prolog to bytecode and runs it. This is the package to reference to embed Prolog in a .NET application.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DotProlog.Runtime\DotProlog.Runtime.csproj" />
        <ProjectReference Include="..\DotProlog.Syntax\DotProlog.Syntax.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DotProlog.Compiler.Tests" />
        <InternalsVisibleTo Include="DotProlog.CodeGen.CSharp" />
    </ItemGroup>
</Project>
