<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>DotProlog.Runtime</RootNamespace>

    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DotProlog.Compiler" />
        <InternalsVisibleTo Include="DotProlog.Runtime.Tests" />
    </ItemGroup>
</Project>
