using System.Globalization;
using System.Text;
using DotProlog.CodeGen.CSharp;
using DotProlog.Syntax;

namespace Integration.Tests;

/// <summary>Emits a temporary runner for the generated-C# conformance matrix.</summary>
internal static class CompiledConformanceSourceGenerator
{
    private static readonly (string Name, int Arity)[] HostBuiltins =
    [
        ("$logtalk_set_text_input", 1),
        ("$logtalk_set_text_input", 2),
        ("$logtalk_delete_text_input", 1),
        ("$logtalk_set_text_output", 1),
        ("$logtalk_set_text_output", 2),
        ("$logtalk_text_output_assertion", 2),
        ("$logtalk_text_output_assertion", 3),
        ("$logtalk_text_output_contents", 1),
        ("$logtalk_text_output_contents", 2),
        ("$logtalk_check_text_output", 2),
        ("$logtalk_file_path", 2),
        ("$logtalk_create_text_file", 2),
        ("$logtalk_create_binary_file", 2),
        ("$logtalk_closed_input_stream", 2),
        ("$logtalk_closed_output_stream", 2),
        ("$logtalk_create_binary_output", 2),
        ("$logtalk_set_named_binary_output", 2),
        ("$logtalk_binary_output_assertion", 2),
        ("$logtalk_binary_output_assertion", 3),
        ("$logtalk_suppress_text_output", 0),
    ];

    internal sealed record SourceGroup(
        string SourcePath,
        string RuntimeSupport,
        IReadOnlyList<(string Name, string Text)> CompiledSupport,
        string Cases,
        IReadOnlyList<(string Name, bool Deterministic)> CasePredicates
    );

    internal static string Generate(IReadOnlyList<SourceGroup> groups, string testsRoot)
    {
        var text = new StringBuilder();
        text.AppendLine("// <auto-generated />");
        text.AppendLine("#nullable enable");
        text.AppendLine("namespace Integration.Tests;");
        text.AppendLine();
        text.AppendLine("internal static class CompiledConformanceGenerated");
        text.AppendLine("{");
        text.AppendLine("    internal static int Run()");
        text.AppendLine("    {");
        text.AppendLine("        int failed = 0;");
        text.AppendLine("        int passed = 0;");
        for (var i = 0; i < groups.Count; i++)
        {
            text.AppendLine(CultureInfo.InvariantCulture, $"        Fixture{i}.Run(ref passed, ref failed);");
        }

        text.AppendLine(
            CultureInfo.InvariantCulture,
            $"        global::System.Console.WriteLine($\"compiled-conformance: {{passed}}/{groups.Sum(group => group.CasePredicates.Count) * 3}, failed={{failed}}\");"
        );
        text.AppendLine("        return failed == 0 ? 0 : 1;");
        text.AppendLine("    }");

        for (var i = 0; i < groups.Count; i++)
        {
            AppendGroup(text, groups[i], i, testsRoot);
        }

        text.AppendLine("}");
        return text.ToString();
    }

    internal static string GenerateStrictIsoSmoke()
    {
        var compiled = CompiledProgramEmitter.Generate(
            [("strict-native.pl", "answer(42).\nnamed_write :- write_term(f(X), [variable_names(['X'=X])]).")],
            "__StrictCompiled",
            [],
            DotProlog.Runtime.PrologLanguageMode.StrictIso,
            out IReadOnlyList<Diagnostic> diagnostics
        );
        if (diagnostics.Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error))
        {
            throw new InvalidOperationException(string.Join("; ", diagnostics));
        }

        return $$"""
            // <auto-generated />
            #nullable enable
            namespace Integration.Tests;

            internal static class StrictIsoGenerated
            {
                internal static int Run()
                {
                    var output = new global::System.IO.StringWriter(
                        global::System.Globalization.CultureInfo.InvariantCulture);
                    var engine = new global::DotProlog.Compiler.PrologEngine(
                        global::DotProlog.Runtime.PrologLanguageMode.StrictIso)
                    {
                        Output = output,
                    };
                    __StrictCompiled.Install(engine);
                    var host = new global::DotProlog.Runtime.PrologHost(engine.Machine);
                    if (!host.Prove(host.Bind("answer", 1), global::DotProlog.Runtime.PrologInput.Integer(42)))
                    {
                        return 1;
                    }

                    if (!host.Prove(host.Bind("named_write", 0))
                        || output.ToString() != "f(X)")
                    {
                        return 2;
                    }

                    global::DotProlog.Compiler.LoadResult rejected =
                        engine.ConsultText("bad :- member(a, [a]).", "strict-runtime.pl");
                    if (rejected.Success
                        || !rejected.Diagnostics.Any(diagnostic =>
                            diagnostic.Id == global::DotProlog.Compiler.CompilerDiagnosticIds.StrictIsoViolation))
                    {
                        return 3;
                    }

                    global::System.Console.WriteLine("strict-iso-native: passed");
                    return 0;
                }

            {{compiled}}
            }
            """;
    }

    internal static string GenerateModernModeSmoke()
    {
        // The clause carries a double-quoted literal, so the bytecode it compiles to is the proof
        // that the build-time reader ran in chars mode.
        var compiled = CompiledProgramEmitter.Generate(
            [("modern-native.pl", "head(L, Ls) :- \"abc\" = [L|Ls].")],
            "__ModernCompiled",
            [],
            DotProlog.Runtime.PrologLanguageMode.Modern,
            out IReadOnlyList<Diagnostic> diagnostics
        );
        if (diagnostics.Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error))
        {
            throw new InvalidOperationException(string.Join("; ", diagnostics));
        }

        return $$"""
            // <auto-generated />
            #nullable enable
            namespace Integration.Tests;

            internal static class ModernModeGenerated
            {
                internal static int Run()
                {
                    var engine = new global::DotProlog.Compiler.PrologEngine(
                        global::DotProlog.Runtime.PrologLanguageMode.Modern);
                    __ModernCompiled.Install(engine);

                    // The clause compiled at build time decomposes its literal as characters.
                    if (engine.RunGoal("head(a, [b,c])", out _)
                        != global::DotProlog.Runtime.RunResult.Success)
                    {
                        return 1;
                    }

                    // The reader running inside the native binary is in chars mode too, so a file
                    // consulted at run time agrees with the one compiled ahead of time.
                    global::DotProlog.Compiler.LoadResult consulted =
                        engine.ConsultText("greeting(G) :- atom_chars(G, \"hi\").", "modern-runtime.pl");
                    if (!consulted.Success)
                    {
                        return 2;
                    }

                    if (engine.RunGoal("greeting(hi)", out _)
                        != global::DotProlog.Runtime.RunResult.Success)
                    {
                        return 3;
                    }

                    // A grammar over characters, translated and run natively.
                    global::DotProlog.Compiler.LoadResult grammar = engine.ConsultText(
                        "digit(D) --> [D], { memberchk(D, \"0123456789\") }.\n"
                            + "digits([D|Ds]) --> digit(D), digits(Ds).\n"
                            + "digits([D]) --> digit(D).\n",
                        "modern-grammar.pl");
                    if (!grammar.Success)
                    {
                        return 4;
                    }

                    if (engine.RunGoal("phrase(digits(['1','2']), \"12\")", out _)
                        != global::DotProlog.Runtime.RunResult.Success)
                    {
                        return 5;
                    }

                    // A load unit that opts out governs only itself.
                    global::DotProlog.Compiler.LoadResult scoped =
                        engine.ConsultText(
                            ":- set_prolog_flag(double_quotes, codes).\niso_style(\"ab\").",
                            "modern-scope.pl");
                    if (!scoped.Success
                        || engine.RunGoal("iso_style([0'a, 0'b])", out _)
                            != global::DotProlog.Runtime.RunResult.Success
                        || engine.RunGoal("current_prolog_flag(double_quotes, chars)", out _)
                            != global::DotProlog.Runtime.RunResult.Success)
                    {
                        return 6;
                    }

                    // Generated code refuses an engine built in a different mode.
                    var extended = new global::DotProlog.Compiler.PrologEngine();
                    try
                    {
                        __ModernCompiled.Install(extended);
                        return 7;
                    }
                    catch (global::DotProlog.Runtime.PrologException)
                    {
                    }

                    global::System.Console.WriteLine("modern-native: passed");
                    return 0;
                }

            {{compiled}}
            }
            """;
    }

    private static void AppendGroup(StringBuilder text, SourceGroup group, int index, string testsRoot)
    {
        IReadOnlyList<(string Name, string Text)> compiledCases = [($"{group.SourcePath}.cases.pl", group.Cases)];
        IReadOnlyList<(string Name, string Text)> combined = [.. group.CompiledSupport, .. compiledCases];
        var all = Emit(combined, "__AllCompiled");
        var cases = Emit(compiledCases, "__CompiledCases");
        var support = Emit(group.CompiledSupport, "__CompiledSupport");

        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"    private static class Fixture{index}");
        text.AppendLine("    {");
        text.AppendLine("        internal static void Run(ref int passed, ref int failed)");
        text.AppendLine("        {");
        text.AppendLine(
            "            RunMode(\"C\", InstallAll, runtimeSupport: false, runtimeCases: false, ref passed, ref failed);"
        );
        text.AppendLine(
            "            RunMode(\"CB\", InstallCases, runtimeSupport: true, runtimeCases: false, ref passed, ref failed);"
        );
        text.AppendLine(
            "            RunMode(\"BC\", InstallSupport, runtimeSupport: false, runtimeCases: true, ref passed, ref failed);"
        );
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine(
            "        private static void RunMode(string mode, global::System.Func<global::DotProlog.Compiler.PrologEngine, int[]> install, bool runtimeSupport, bool runtimeCases, ref int passed, ref int failed)"
        );
        text.AppendLine("        {");
        text.AppendLine(
            $"            var engine = LogtalkConformanceTests.CreateAdapterEngine(global::System.IO.Path.Combine(global::System.IO.Path.GetTempPath(), \"dotprolog-compiled-{index}-\" + mode));"
        );
        text.AppendLine("            try");
        text.AppendLine("            {");
        text.AppendLine("                if (runtimeSupport)");
        text.AppendLine("                {");
        text.AppendLine(
            $"                    LogtalkConformanceTests.LoadAdapterSupport(engine, {Literal(group.SourcePath)}, {Literal(group.RuntimeSupport)}, {Literal(testsRoot)});"
        );
        text.AppendLine("                }");
        text.AppendLine("                int[] initialization = install(engine);");
        text.AppendLine("                foreach (int target in initialization)");
        text.AppendLine("                {");
        text.AppendLine("                    if (engine.Machine.Run(target) is not global::DotProlog.Runtime.RunResult.Success)");
        text.AppendLine("                    {");
        text.AppendLine(
            "                        throw new global::System.InvalidOperationException(\"compiled initialization failed\");"
        );
        text.AppendLine("                    }");
        text.AppendLine("                }");
        text.AppendLine("                if (runtimeCases)");
        text.AppendLine("                {");
        text.AppendLine(
            $"                    global::DotProlog.Compiler.LoadResult loaded = engine.ConsultText({Literal(group.Cases)}, {Literal(group.SourcePath + ".cases.pl")});"
        );
        text.AppendLine("                    if (!loaded.Success)");
        text.AppendLine("                    {");
        text.AppendLine(
            "                        throw new global::System.InvalidOperationException(string.Join(\"; \", loaded.Diagnostics));"
        );
        text.AppendLine("                    }");
        text.AppendLine("                }");
        text.AppendLine("                var host = new global::DotProlog.Runtime.PrologHost(engine.Machine);");

        foreach ((var name, var deterministic) in group.CasePredicates)
        {
            text.AppendLine("                try");
            text.AppendLine("                {");
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"                    bool proved = host.Prove(host.Bind({Literal(name)}, 0));"
            );
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"                    if (!proved{(deterministic ? " || engine.Machine.HasAlternatives" : string.Empty)})"
            );
            text.AppendLine("                    {");
            text.AppendLine("                        failed++;");
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"                        global::System.Console.Error.WriteLine($\"{{mode}} | {Escape(group.SourcePath)} | {Escape(name)} | failed\");"
            );
            text.AppendLine("                    }");
            text.AppendLine("                    else");
            text.AppendLine("                    {");
            text.AppendLine("                        passed++;");
            text.AppendLine("                    }");
            text.AppendLine("                }");
            text.AppendLine("                catch (global::System.Exception error)");
            text.AppendLine("                {");
            text.AppendLine("                    failed++;");
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"                    global::System.Console.Error.WriteLine($\"{{mode}} | {Escape(group.SourcePath)} | {Escape(name)} | {{error.Message}}\");"
            );
            text.AppendLine("                }");

            // A case that leaks an open stream must not hold a file lock into the next case;
            // Windows enforces sharing, so leaked writers make later opens fail.
            text.AppendLine("                engine.Machine.Streams.CloseAll();");
        }

        text.AppendLine("            }");
        text.AppendLine("            finally");
        text.AppendLine("            {");
        text.AppendLine("                engine.Machine.Streams.CloseAll();");
        text.AppendLine("            }");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine(
            "        private static int[] InstallAll(global::DotProlog.Compiler.PrologEngine engine) => __AllCompiled.Install(engine);"
        );
        text.AppendLine(
            "        private static int[] InstallCases(global::DotProlog.Compiler.PrologEngine engine) => __CompiledCases.Install(engine);"
        );
        text.AppendLine(
            "        private static int[] InstallSupport(global::DotProlog.Compiler.PrologEngine engine) => __CompiledSupport.Install(engine);"
        );
        text.AppendLine();
        text.Append(all);
        text.AppendLine();
        text.Append(cases);
        text.AppendLine();
        text.Append(support);
        text.AppendLine("    }");
    }

    private static string Emit(IReadOnlyList<(string Name, string Text)> sources, string typeName)
    {
        var generated = CompiledProgramEmitter.Generate(
            sources,
            typeName,
            HostBuiltins,
            out IReadOnlyList<Diagnostic> diagnostics
        );
        if (diagnostics.Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error))
        {
            throw new InvalidOperationException(string.Join("; ", diagnostics));
        }

        return generated;
    }

    private static string Literal(string value) => SyntaxFacts.Literal(value);

    private static string Escape(string value) =>
        value.Replace("{", "{{", StringComparison.Ordinal).Replace("}", "}}", StringComparison.Ordinal);
}
