using System.Globalization;
using System.Text;

namespace Prolog.CodeGen.CSharp;

/// <summary>
/// Emits the entry point for a <c>.dplproj</c> built as an application, so that Prolog is a language
/// you can write a program in rather than only a library other languages call.
/// </summary>
/// <remarks>
/// The program's sources are embedded and consulted at startup, then its <c>:- initialization</c>
/// goals run. Exit codes follow the <c>dotnet prolog</c> tool: the code <c>halt/1</c> asked for, 1 for
/// a goal that failed, and 70 for a ball nothing caught.
/// </remarks>
public static class EntryPointGenerator
{
    /// <summary>The type name generated, which the SDK points <c>StartupObject</c> at.</summary>
    public const string TypeName = "PrologProgram";

    /// <summary>Generates the entry point for <paramref name="sources"/>.</summary>
    /// <param name="namespace">Namespace to generate into.</param>
    /// <param name="sources">Each source file's name and contents, consulted in order.</param>
    public static string Generate(string @namespace, IReadOnlyList<(string Name, string Text)> sources)
    {
        ArgumentNullException.ThrowIfNull(@namespace);
        ArgumentNullException.ThrowIfNull(sources);

        var text = new StringBuilder();

        text.AppendLine("// <auto-generated />");
        text.AppendLine("// Generated by Prolog.CodeGen.CSharp. Edit the .pl files instead.");
        text.AppendLine("#nullable enable");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"namespace {@namespace};");
        text.AppendLine();
        text.AppendLine("/// <summary>Entry point for a Prolog application.</summary>");
        text.AppendLine(CultureInfo.InvariantCulture, $"internal static class {TypeName}");
        text.AppendLine("{");

        for (int i = 0; i < sources.Count; i++)
        {
            text.AppendLine(CultureInfo.InvariantCulture, $"    private const string Source{i} = {Literal(sources[i].Text)};");
        }

        text.AppendLine();
        text.AppendLine("    private static int Main()");
        text.AppendLine("    {");
        text.AppendLine("        var engine = new global::Prolog.Compiler.PrologEngine();");
        text.AppendLine();

        for (int i = 0; i < sources.Count; i++)
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"        engine.ConsultOrThrow(Source{i}, {Literal(sources[i].Name)});"
            );
        }

        text.AppendLine();
        text.AppendLine("        try");
        text.AppendLine("        {");
        text.AppendLine("            global::Prolog.Runtime.RunResult result = engine.RunPendingGoals();");
        text.AppendLine("            global::System.Console.Out.Flush();");
        text.AppendLine();
        text.AppendLine("            return result switch");
        text.AppendLine("            {");
        text.AppendLine("                global::Prolog.Runtime.RunResult.Halted => engine.Machine.ExitCode,");
        text.AppendLine("                global::Prolog.Runtime.RunResult.Failure => 1,");
        text.AppendLine("                _ => 0,");
        text.AppendLine("            };");
        text.AppendLine("        }");
        text.AppendLine("        catch (global::Prolog.Runtime.PrologException error)");
        text.AppendLine("        {");
        text.AppendLine("            global::System.Console.Out.Flush();");
        text.AppendLine("            global::System.Console.Error.WriteLine($\"error: {error.Message}\");");
        text.AppendLine("            return 70;");
        text.AppendLine("        }");
        text.AppendLine("    }");
        text.AppendLine("}");

        return text.ToString();
    }

    private static string Literal(string value) =>
        $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal).Replace("\r", "\\r", StringComparison.Ordinal).Replace("\n", "\\n", StringComparison.Ordinal)}\"";
}
