using System.Globalization;
using System.Text;

namespace Prolog.CodeGen.CSharp;

/// <summary>
/// Emits the typed C# facade for a module, so that C#, F#, and VB callers see ordinary .NET methods
/// instead of goal strings.
/// </summary>
/// <remarks>
/// <para>
/// The determinism of each export decides its signature, per [ADR 0006]: <c>det</c> returns its
/// output, <c>semidet</c> returns <see langword="bool"/> or a <c>TryX</c> pair, and <c>multi</c> and
/// <c>nondet</c> return an enumerable that streams solutions as the caller pulls them.
/// </para>
/// <para>
/// The module's Prolog source is embedded as a constant and consulted when the facade is created.
/// Embedding compiled bytecode instead would start faster and would let a facade run against
/// <c>Prolog.Runtime</c> alone; that is a later step, and it changes nothing about this surface.
/// </para>
/// </remarks>
public static class FacadeGenerator
{
    /// <summary>Generates the facade source for <paramref name="contract"/>.</summary>
    /// <param name="contract">The module surface to generate.</param>
    /// <param name="prologSource">The module's Prolog source, embedded and consulted at construction.</param>
    /// <param name="sourceName">Name reported in diagnostics if the embedded source fails to load.</param>
    public static string Generate(ModuleContract contract, string prologSource, string sourceName)
    {
        ArgumentNullException.ThrowIfNull(contract);
        ArgumentNullException.ThrowIfNull(prologSource);
        ArgumentNullException.ThrowIfNull(sourceName);

        var text = new StringBuilder();

        text.AppendLine("// <auto-generated />");
        text.AppendLine("// Generated by Prolog.CodeGen.CSharp. Edit the .pl and .dpli files instead.");
        text.AppendLine("#nullable enable");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"namespace {contract.Namespace};");
        text.AppendLine();

        AppendResultTypes(text, contract);
        AppendInterface(text, contract);
        AppendImplementation(text, contract, prologSource, sourceName);

        return text.ToString();
    }

    private static void AppendResultTypes(StringBuilder text, ModuleContract contract)
    {
        foreach (ContractExport export in contract.Exports.Where(e => e.Outputs.Count() > 1))
        {
            string members = string.Join(
                ", ",
                export.Outputs.Select(output => $"{output.Type.ClrTypeName} {Pascal(output.Name)}")
            );

            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"/// <summary>The outputs of <c>{export.PredicateName}/{export.Arity}</c>.</summary>"
            );
            text.AppendLine(CultureInfo.InvariantCulture, $"public readonly record struct {ResultTypeName(export)}({members});");
            text.AppendLine();
        }
    }

    private static void AppendInterface(StringBuilder text, ModuleContract contract)
    {
        text.AppendLine(
            CultureInfo.InvariantCulture,
            $"/// <summary>The Prolog module <c>{contract.ClrTypeName}</c>, callable from .NET.</summary>"
        );
        text.AppendLine(CultureInfo.InvariantCulture, $"public partial interface I{contract.ClrTypeName}Module");
        text.AppendLine("{");

        foreach (ContractExport export in contract.Exports)
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"    /// <summary>Calls <c>{export.PredicateName}/{export.Arity}</c> ({Lower(export.Determinism)}).</summary>"
            );
            text.AppendLine(CultureInfo.InvariantCulture, $"    {Signature(export)};");
            text.AppendLine();
        }

        text.Length -= Environment.NewLine.Length;
        text.AppendLine("}");
        text.AppendLine();
    }

    private static void AppendImplementation(StringBuilder text, ModuleContract contract, string prologSource, string sourceName)
    {
        string type = $"{contract.ClrTypeName}Module";

        text.AppendLine(
            CultureInfo.InvariantCulture,
            $"/// <summary>The generated implementation of <see cref=\"I{type}\"/>.</summary>"
        );
        text.AppendLine(
            "/// <remarks>An instance owns a machine, so it runs one call at a time and is not thread-safe.</remarks>"
        );
        text.AppendLine(CultureInfo.InvariantCulture, $"public sealed partial class {type} : I{type}");
        text.AppendLine("{");
        text.AppendLine(CultureInfo.InvariantCulture, $"    private const string PrologSource = {Literal(prologSource)};");
        text.AppendLine();
        text.AppendLine("    private readonly global::Prolog.Runtime.PrologHost _host;");

        foreach (ContractExport export in contract.Exports)
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"    private readonly global::Prolog.Runtime.PrologPredicate {Field(export)};"
            );
        }

        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"    private {type}(global::Prolog.Compiler.PrologEngine engine)");
        text.AppendLine("    {");
        text.AppendLine("        _host = new global::Prolog.Runtime.PrologHost(engine.Machine);");

        foreach (ContractExport export in contract.Exports)
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"        {Field(export)} = _host.Bind(\"{export.PredicateName}\", {export.Arity});"
            );
        }

        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    /// <summary>Loads the module into a fresh engine.</summary>");
        text.AppendLine(CultureInfo.InvariantCulture, $"    public static I{type} Create()");
        text.AppendLine("    {");
        text.AppendLine("        var engine = new global::Prolog.Compiler.PrologEngine();");
        text.AppendLine(CultureInfo.InvariantCulture, $"        engine.ConsultOrThrow(PrologSource, {Literal(sourceName)});");
        text.AppendLine("        engine.RunPendingGoals();");
        text.AppendLine(CultureInfo.InvariantCulture, $"        return new {type}(engine);");
        text.AppendLine("    }");

        foreach (ContractExport export in contract.Exports)
        {
            text.AppendLine();
            AppendMethod(text, export);
        }

        text.AppendLine("}");
    }

    private static void AppendMethod(StringBuilder text, ContractExport export)
    {
        string arguments = string.Join(
            ", ",
            export.Arguments.Select(argument =>
                argument.Mode == ArgumentMode.In
                    ? argument.Type.ToInputExpression(Camel(argument.Name))
                    : "global::Prolog.Runtime.PrologInput.Output"
            )
        );

        string call = arguments.Length == 0 ? Field(export) : $"{Field(export)}, {arguments}";

        text.AppendLine("    /// <inheritdoc />");
        text.AppendLine(CultureInfo.InvariantCulture, $"    public {Signature(export)}");
        text.AppendLine("    {");

        if (export.IsStreaming)
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"        foreach (global::Prolog.Runtime.PrologValue[] __outputs in _host.CallAll({call}))"
            );
            text.AppendLine("        {");
            text.AppendLine(CultureInfo.InvariantCulture, $"            yield return {ResultExpression(export)};");
            text.AppendLine("        }");
        }
        else if (!export.Outputs.Any())
        {
            text.AppendLine(CultureInfo.InvariantCulture, $"        return _host.Prove({call});");
        }
        else if (export.Determinism == Determinism.Det)
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"        global::Prolog.Runtime.PrologValue[] __outputs = _host.CallOnce({call})"
            );
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"            ?? throw new global::Prolog.Runtime.PrologException(\"{export.PredicateName}/{export.Arity} is declared det but failed.\");"
            );
            text.AppendLine(CultureInfo.InvariantCulture, $"        return {ResultExpression(export)};");
        }
        else
        {
            // semidet with outputs: the TryX pair, so failure is not an exception.
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"        global::Prolog.Runtime.PrologValue[]? __outputs = _host.CallOnce({call});"
            );
            text.AppendLine("        if (__outputs is null)");
            text.AppendLine("        {");
            text.AppendLine(CultureInfo.InvariantCulture, $"            {ResultParameterName(export)} = default!;");
            text.AppendLine("            return false;");
            text.AppendLine("        }");
            text.AppendLine();
            text.AppendLine(CultureInfo.InvariantCulture, $"        {ResultParameterName(export)} = {ResultExpression(export)};");
            text.AppendLine("        return true;");
        }

        text.AppendLine("    }");
    }

    private static string Signature(ContractExport export)
    {
        string parameters = string.Join(", ", export.Inputs.Select(input => $"{input.Type.ClrTypeName} {Camel(input.Name)}"));

        string name = MethodName(export);

        if (export.IsStreaming)
        {
            return $"global::System.Collections.Generic.IEnumerable<{ResultTypeExpression(export)}> {name}({parameters})";
        }

        if (!export.Outputs.Any())
        {
            return $"bool {name}({parameters})";
        }

        if (export.Determinism == Determinism.Det)
        {
            return $"{ResultTypeExpression(export)} {name}({parameters})";
        }

        string separator = parameters.Length == 0 ? string.Empty : ", ";
        return $"bool Try{name}({parameters}{separator}out {ResultTypeExpression(export)} {ResultParameterName(export)})";
    }

    private static string ResultTypeExpression(ContractExport export) =>
        export.Outputs.Count() > 1 ? ResultTypeName(export) : export.Outputs.First().Type.ClrTypeName;

    private static string ResultExpression(ContractExport export)
    {
        ContractArgument[] outputs = [.. export.Outputs];

        if (outputs.Length == 1)
        {
            return outputs[0].Type.ToOutputExpression("__outputs[0]");
        }

        string members = string.Join(
            ", ",
            outputs.Select((output, index) => output.Type.ToOutputExpression($"__outputs[{index}]"))
        );

        return $"new {ResultTypeName(export)}({members})";
    }

    private static string ResultParameterName(ContractExport export) =>
        export.Outputs.Count() > 1 ? "result" : Camel(export.Outputs.First().Name);

    private static string ResultTypeName(ContractExport export) => $"{MethodName(export)}Result";

    private static string MethodName(ContractExport export) => Pascal(export.PredicateName);

    private static string Field(ContractExport export) => $"_{Camel(export.PredicateName)}{export.Arity}";

    private static string Lower(Determinism determinism) => determinism.ToString().ToLowerInvariant();

    /// <summary>Turns a Prolog identifier such as <c>in_stock</c> into <c>InStock</c>.</summary>
    private static string Pascal(string name)
    {
        var text = new StringBuilder(name.Length);
        bool upper = true;

        foreach (char c in name)
        {
            if (c == '_')
            {
                upper = true;
                continue;
            }

            text.Append(upper ? char.ToUpperInvariant(c) : c);
            upper = false;
        }

        return text.Length == 0 ? "Predicate" : text.ToString();
    }

    private static string Camel(string name)
    {
        string pascal = Pascal(name);
        string camel = char.ToLowerInvariant(pascal[0]) + pascal[1..];
        return SyntaxFacts.IsKeyword(camel) ? "@" + camel : camel;
    }

    private static string Literal(string value) =>
        $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal).Replace("\r", "\\r", StringComparison.Ordinal).Replace("\n", "\\n", StringComparison.Ordinal)}\"";
}
