<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Prolog.CodeGen.CSharp</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Prolog.Compiler\Prolog.Compiler.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Prolog.CodeGen.CSharp.Tests" />
    </ItemGroup>
</Project>
