<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>DotProlog.Testing</RootNamespace>

    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Testing.Platform" Version="2.3.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DotProlog.Compiler\DotProlog.Compiler.csproj" />
    </ItemGroup>
</Project>
