<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Prolog.Compiler.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Prolog.Compiler\Prolog.Compiler.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\samples\HelloProlog\hello.pl" Link="hello.pl" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
