<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>DotProlog.CodeGen.CSharp</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DotProlog.Compiler\DotProlog.Compiler.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DotProlog.CodeGen.CSharp.Tests" />
        <InternalsVisibleTo Include="Integration.Tests" />
    </ItemGroup>
</Project>
