using System.Globalization;
using System.Text;

namespace DotProlog.CodeGen.CSharp;

/// <summary>
/// Emits the entry point for a <c>.dplproj</c> built as an application, so that Prolog is a language
/// you can write a program in rather than only a library other languages call.
/// </summary>
/// <remarks>
/// The program's sources are lowered to generated C# at build time, then its
/// <c>:- initialization</c> goals run. Exit codes follow the <c>dotnet prolog</c> tool: the code
/// <c>halt/1</c> asked for, 1 for a goal that failed, and 70 for a ball nothing caught.
/// </remarks>
public static class EntryPointGenerator
{
    /// <summary>The type name generated, which the SDK points <c>StartupObject</c> at.</summary>
    public const string TypeName = "PrologProgram";

    /// <summary>
    /// Generates a test host entry point, which hands the sources to Microsoft.Testing.Platform so
    /// that <c>dotnet test</c> discovers and runs the project's <c>test_*</c> predicates.
    /// </summary>
    /// <param name="namespace">Namespace to generate into.</param>
    /// <param name="sources">Each source file's name and contents.</param>
    public static string GenerateTestHost(string @namespace, IReadOnlyList<(string Name, string Text)> sources)
    {
        ArgumentNullException.ThrowIfNull(@namespace);
        ArgumentNullException.ThrowIfNull(sources);

        string compiledProgram = CompiledProgramEmitter.Generate(
            sources,
            "__CompiledTests",
            out IReadOnlyList<DotProlog.Syntax.Diagnostic> diagnostics
        );
        if (diagnostics.Any(diagnostic => diagnostic.Severity == DotProlog.Syntax.DiagnosticSeverity.Error))
        {
            throw new ArgumentException($"Prolog tests did not compile: {string.Join("; ", diagnostics)}", nameof(sources));
        }

        var text = new StringBuilder();

        AppendHeader(text, @namespace);
        text.AppendLine("/// <summary>Entry point for a Prolog test project.</summary>");
        text.AppendLine(CultureInfo.InvariantCulture, $"internal static class {TypeName}");
        text.AppendLine("{");
        text.AppendLine("    private static global::System.Threading.Tasks.Task<int> Main(string[] args) =>");
        text.AppendLine("        global::DotProlog.Testing.PrologTestHost.RunAsync(args, CreateEngine);");
        text.AppendLine();
        text.AppendLine("    private static global::DotProlog.Compiler.PrologEngine CreateEngine()");
        text.AppendLine("    {");
        text.AppendLine("        var engine = new global::DotProlog.Compiler.PrologEngine();");
        text.AppendLine("        int[] initialization = __CompiledTests.Install(engine);");
        text.AppendLine("        foreach (int target in initialization)");
        text.AppendLine("        {");
        text.AppendLine("            engine.Machine.Run(target);");
        text.AppendLine("        }");
        text.AppendLine();
        text.AppendLine("        return engine;");
        text.AppendLine("    }");
        text.AppendLine();
        text.Append(compiledProgram);
        text.AppendLine("}");

        return text.ToString();
    }

    private static void AppendHeader(StringBuilder text, string @namespace)
    {
        text.AppendLine("// <auto-generated />");
        text.AppendLine("// Generated by DotProlog.CodeGen.CSharp. Edit the .pl files instead.");
        text.AppendLine("#nullable enable");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"namespace {@namespace};");
        text.AppendLine();
    }

    /// <summary>Generates the entry point for <paramref name="sources"/>.</summary>
    /// <param name="namespace">Namespace to generate into.</param>
    /// <param name="sources">Each source file's name and contents, consulted in order.</param>
    public static string Generate(string @namespace, IReadOnlyList<(string Name, string Text)> sources)
    {
        ArgumentNullException.ThrowIfNull(@namespace);
        ArgumentNullException.ThrowIfNull(sources);

        string compiledProgram = CompiledProgramEmitter.Generate(
            sources,
            "__CompiledProgram",
            out IReadOnlyList<DotProlog.Syntax.Diagnostic> diagnostics
        );
        if (diagnostics.Any(diagnostic => diagnostic.Severity == DotProlog.Syntax.DiagnosticSeverity.Error))
        {
            throw new ArgumentException($"Prolog sources did not compile: {string.Join("; ", diagnostics)}", nameof(sources));
        }

        var text = new StringBuilder();

        text.AppendLine("// <auto-generated />");
        text.AppendLine("// Generated by DotProlog.CodeGen.CSharp. Edit the .pl files instead.");
        text.AppendLine("#nullable enable");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"namespace {@namespace};");
        text.AppendLine();
        text.AppendLine("/// <summary>Entry point for a Prolog application.</summary>");
        text.AppendLine(CultureInfo.InvariantCulture, $"internal static class {TypeName}");
        text.AppendLine("{");

        text.AppendLine("    private static int Main()");
        text.AppendLine("    {");
        text.AppendLine("        var engine = new global::DotProlog.Compiler.PrologEngine();");
        text.AppendLine("        int[] initialization = __CompiledProgram.Install(engine);");
        text.AppendLine("        try");
        text.AppendLine("        {");
        text.AppendLine("            global::DotProlog.Runtime.RunResult result = global::DotProlog.Runtime.RunResult.Success;");
        text.AppendLine("            foreach (int target in initialization)");
        text.AppendLine("            {");
        text.AppendLine("                result = engine.Machine.Run(target);");
        text.AppendLine("                if (result is global::DotProlog.Runtime.RunResult.Halted)");
        text.AppendLine("                {");
        text.AppendLine("                    break;");
        text.AppendLine("                }");
        text.AppendLine("            }");
        text.AppendLine("            global::System.Console.Out.Flush();");
        text.AppendLine();
        text.AppendLine("            return result switch");
        text.AppendLine("            {");
        text.AppendLine("                global::DotProlog.Runtime.RunResult.Halted => engine.Machine.ExitCode,");
        text.AppendLine("                global::DotProlog.Runtime.RunResult.Failure => 1,");
        text.AppendLine("                _ => 0,");
        text.AppendLine("            };");
        text.AppendLine("        }");
        text.AppendLine("        catch (global::DotProlog.Runtime.PrologException error)");
        text.AppendLine("        {");
        text.AppendLine("            global::System.Console.Out.Flush();");
        text.AppendLine("            global::System.Console.Error.WriteLine($\"error: {error.Message}\");");
        text.AppendLine("            return 70;");
        text.AppendLine("        }");
        text.AppendLine("    }");
        text.AppendLine();
        text.Append(compiledProgram);
        text.AppendLine("}");

        return text.ToString();
    }

    private static string Literal(string value) =>
        $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal).Replace("\r", "\\r", StringComparison.Ordinal).Replace("\n", "\\n", StringComparison.Ordinal)}\"";
}
