using System.Globalization;
using System.Text;
using DotProlog.Runtime;

namespace DotProlog.CodeGen.CSharp;

/// <summary>
/// Emits the typed C# facade for a module, so that C#, F#, and VB callers see ordinary .NET methods
/// instead of goal strings.
/// </summary>
/// <remarks>
/// <para>
/// The determinism of each export decides its signature, per [ADR 0006]: <c>det</c> returns its
/// output, <c>semidet</c> returns <see langword="bool"/> or a <c>TryX</c> pair, and <c>multi</c> and
/// <c>nondet</c> return an enumerable that streams solutions as the caller pulls them.
/// </para>
/// <para>
/// The module's Prolog source is lowered at build time into direct-threaded generated C# blocks.
/// Runtime consultation remains available through the engine, but constructing a facade does not
/// parse or compile its build-time source.
/// </para>
/// </remarks>
public static class FacadeGenerator
{
    /// <summary>Generates the facade source for <paramref name="contract"/>.</summary>
    /// <param name="contract">The module surface to generate.</param>
    /// <param name="prologSource">The module's Prolog source, compiled into generated C# blocks.</param>
    /// <param name="sourceName">Name reported in build-time diagnostics.</param>
    public static string Generate(ModuleContract contract, string prologSource, string sourceName) =>
        Generate(contract, prologSource, sourceName, PrologLanguageMode.Extended);

    /// <summary>Generates a facade whose build-time and runtime behavior use <paramref name="languageMode"/>.</summary>
    public static string Generate(
        ModuleContract contract,
        string prologSource,
        string sourceName,
        PrologLanguageMode languageMode
    )
    {
        ArgumentNullException.ThrowIfNull(contract);
        ArgumentNullException.ThrowIfNull(prologSource);
        ArgumentNullException.ThrowIfNull(sourceName);

        var text = new StringBuilder();

        text.AppendLine("// <auto-generated />");
        text.AppendLine("// Generated by DotProlog.CodeGen.CSharp. Edit the .pl and .dpli files instead.");
        text.AppendLine("#nullable enable");
        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"namespace {contract.Namespace};");
        text.AppendLine();

        AppendResultTypes(text, contract);
        AppendInterface(text, contract);
        string compiledProgram = CompiledProgramEmitter.Generate(
            [(sourceName, prologSource)],
            "__CompiledModule",
            [],
            languageMode,
            out IReadOnlyList<DotProlog.Syntax.Diagnostic> diagnostics
        );
        if (diagnostics.Any(diagnostic => diagnostic.Severity == DotProlog.Syntax.DiagnosticSeverity.Error))
        {
            throw new ArgumentException($"{sourceName} did not compile: {string.Join("; ", diagnostics)}", nameof(prologSource));
        }

        AppendImplementation(text, contract, compiledProgram, languageMode);

        return text.ToString();
    }

    private static void AppendResultTypes(StringBuilder text, ModuleContract contract)
    {
        foreach (ContractExport export in contract.Exports.Where(e => e.Outputs.Count() > 1))
        {
            string members = string.Join(
                ", ",
                export.Outputs.Select(output => $"{output.Type.ClrTypeName} {Pascal(output.Name)}")
            );

            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"/// <summary>The outputs of <c>{export.PredicateName}/{export.Arity}</c>.</summary>"
            );
            text.AppendLine(CultureInfo.InvariantCulture, $"public readonly record struct {ResultTypeName(export)}({members});");
            text.AppendLine();
        }
    }

    private static void AppendInterface(StringBuilder text, ModuleContract contract)
    {
        text.AppendLine(
            CultureInfo.InvariantCulture,
            $"/// <summary>The Prolog module <c>{contract.ClrTypeName}</c>, callable from .NET.</summary>"
        );
        text.AppendLine(CultureInfo.InvariantCulture, $"public partial interface I{contract.ClrTypeName}Module");
        text.AppendLine("{");

        foreach (ContractExport export in contract.Exports)
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"    /// <summary>Calls <c>{export.PredicateName}/{export.Arity}</c> ({Lower(export.Determinism)}).</summary>"
            );
            text.AppendLine(CultureInfo.InvariantCulture, $"    {Signature(export)};");
            text.AppendLine();
        }

        text.Length -= Environment.NewLine.Length;
        text.AppendLine("}");
        text.AppendLine();
    }

    private static void AppendImplementation(
        StringBuilder text,
        ModuleContract contract,
        string compiledProgram,
        PrologLanguageMode languageMode
    )
    {
        string type = $"{contract.ClrTypeName}Module";

        text.AppendLine(
            CultureInfo.InvariantCulture,
            $"/// <summary>The generated implementation of <see cref=\"I{type}\"/>.</summary>"
        );
        text.AppendLine(
            "/// <remarks>An instance owns a machine, so it runs one call at a time and is not thread-safe.</remarks>"
        );
        text.AppendLine(CultureInfo.InvariantCulture, $"public sealed partial class {type} : I{type}");
        text.AppendLine("{");
        text.AppendLine("    private readonly global::DotProlog.Runtime.PrologHost _host;");

        foreach (ContractExport export in contract.Exports)
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"    private readonly global::DotProlog.Runtime.PrologPredicate {Field(export)};"
            );
        }

        text.AppendLine();
        text.AppendLine(CultureInfo.InvariantCulture, $"    private {type}(global::DotProlog.Compiler.PrologEngine engine)");
        text.AppendLine("    {");
        text.AppendLine("        _host = new global::DotProlog.Runtime.PrologHost(engine.Machine);");

        foreach (ContractExport export in contract.Exports)
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"        {Field(export)} = _host.Bind({SyntaxFacts.Literal(export.PredicateName)}, {export.Arity});"
            );
        }

        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    /// <summary>Loads the module into a fresh engine.</summary>");
        text.AppendLine(CultureInfo.InvariantCulture, $"    public static I{type} Create()");
        text.AppendLine("    {");
        text.AppendLine(
            CultureInfo.InvariantCulture,
            $"        var engine = new global::DotProlog.Compiler.PrologEngine(global::DotProlog.Runtime.PrologLanguageMode.{languageMode});"
        );
        text.AppendLine("        return Create(engine);");
        text.AppendLine("    }");
        text.AppendLine();
        text.AppendLine("    /// <summary>Loads the module into an existing engine.</summary>");
        text.AppendLine(
            CultureInfo.InvariantCulture,
            $"    public static I{type} Create(global::DotProlog.Compiler.PrologEngine engine)"
        );
        text.AppendLine("    {");
        text.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(engine);");
        text.AppendLine("        int[] initialization = __CompiledModule.Install(engine);");
        text.AppendLine("        foreach (int target in initialization)");
        text.AppendLine("        {");
        text.AppendLine("            engine.Machine.Run(target);");
        text.AppendLine("        }");
        text.AppendLine(CultureInfo.InvariantCulture, $"        return new {type}(engine);");
        text.AppendLine("    }");

        foreach (ContractExport export in contract.Exports)
        {
            text.AppendLine();
            AppendMethod(text, export);
        }

        text.AppendLine();
        text.Append(compiledProgram);
        text.AppendLine("}");
    }

    private static void AppendMethod(StringBuilder text, ContractExport export)
    {
        string arguments = string.Join(
            ", ",
            export.Arguments.Select(argument =>
                argument.Mode == ArgumentMode.In
                    ? argument.Type.ToInputExpression(Camel(argument.Name))
                    : "global::DotProlog.Runtime.PrologInput.Output"
            )
        );

        string call = arguments.Length == 0 ? Field(export) : $"{Field(export)}, {arguments}";

        text.AppendLine("    /// <inheritdoc />");
        text.AppendLine(CultureInfo.InvariantCulture, $"    public {Signature(export)}");
        text.AppendLine("    {");

        AppendNullGuards(text, export);

        if (export.IsStreaming)
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"        foreach (global::DotProlog.Runtime.PrologValue[] __outputs in _host.CallAll({call}))"
            );
            text.AppendLine("        {");
            text.AppendLine("            cancellationToken.ThrowIfCancellationRequested();");
            text.AppendLine(CultureInfo.InvariantCulture, $"            yield return {ResultExpression(export)};");
            text.AppendLine("        }");
        }
        else if (!export.Outputs.Any())
        {
            text.AppendLine(CultureInfo.InvariantCulture, $"        return _host.Prove({call});");
        }
        else if (export.Determinism == Determinism.Det)
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"        global::DotProlog.Runtime.PrologValue[] __outputs = _host.CallOnce({call})"
            );
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"            ?? throw new global::DotProlog.Runtime.PrologException({SyntaxFacts.Literal($"{export.PredicateName}/{export.Arity} is declared det but failed.")});"
            );
            text.AppendLine(CultureInfo.InvariantCulture, $"        return {ResultExpression(export)};");
        }
        else
        {
            // semidet with outputs: the TryX pair, so failure is not an exception.
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"        global::DotProlog.Runtime.PrologValue[]? __outputs = _host.CallOnce({call});"
            );
            text.AppendLine("        if (__outputs is null)");
            text.AppendLine("        {");
            text.AppendLine(CultureInfo.InvariantCulture, $"            {ResultParameterName(export)} = default!;");
            text.AppendLine("            return false;");
            text.AppendLine("        }");
            text.AppendLine();
            text.AppendLine(CultureInfo.InvariantCulture, $"        {ResultParameterName(export)} = {ResultExpression(export)};");
            text.AppendLine("        return true;");
        }

        text.AppendLine("    }");
    }

    /// <summary>
    /// Emits a null check for every reference-typed input.
    /// </summary>
    /// <remarks>
    /// The F# component design guidelines call for checking null at a vanilla .NET API boundary,
    /// because callers in other languages use null far more freely than the implementation language
    /// does. Without this a null list fails somewhere inside the marshalling instead of naming the
    /// parameter that was wrong.
    /// </remarks>
    private static void AppendNullGuards(StringBuilder text, ContractExport export)
    {
        bool wrote = false;

        foreach (ContractArgument input in export.Inputs.Where(input => IsReferenceType(input.Type)))
        {
            text.AppendLine(
                CultureInfo.InvariantCulture,
                $"        global::System.ArgumentNullException.ThrowIfNull({Camel(input.Name)});"
            );

            wrote = true;
        }

        if (wrote)
        {
            text.AppendLine();
        }
    }

    private static bool IsReferenceType(ContractType type) =>
        type.Kind is ContractTypeKind.Atom or ContractTypeKind.List or ContractTypeKind.Term;

    private static string Signature(ContractExport export)
    {
        string parameters = string.Join(", ", export.Inputs.Select(input => $"{input.Type.ClrTypeName} {Camel(input.Name)}"));

        string name = MethodName(export);

        if (export.IsStreaming)
        {
            // A streaming call can enumerate for as long as the caller keeps pulling, so it has to be
            // possible to stop it. .NET expects that to be a CancellationToken.
            string before = parameters.Length == 0 ? string.Empty : ", ";
            return $"global::System.Collections.Generic.IEnumerable<{ResultTypeExpression(export)}> {name}({parameters}{before}"
                + "global::System.Threading.CancellationToken cancellationToken = default)";
        }

        if (!export.Outputs.Any())
        {
            return $"bool {name}({parameters})";
        }

        if (export.Determinism == Determinism.Det)
        {
            return $"{ResultTypeExpression(export)} {name}({parameters})";
        }

        string separator = parameters.Length == 0 ? string.Empty : ", ";
        return $"bool Try{name}({parameters}{separator}out {ResultTypeExpression(export)} {ResultParameterName(export)})";
    }

    private static string ResultTypeExpression(ContractExport export) =>
        export.Outputs.Count() switch
        {
            // nondet with no outputs streams its successes, per ADR 0006's determinism table.
            0 => "global::DotProlog.Runtime.Unit",
            1 => export.Outputs.First().Type.ClrTypeName,
            _ => ResultTypeName(export),
        };

    private static string ResultExpression(ContractExport export)
    {
        ContractArgument[] outputs = [.. export.Outputs];

        if (outputs.Length == 0)
        {
            return "global::DotProlog.Runtime.Unit.Value";
        }

        if (outputs.Length == 1)
        {
            return outputs[0].Type.ToOutputExpression("__outputs[0]");
        }

        string members = string.Join(
            ", ",
            outputs.Select((output, index) => output.Type.ToOutputExpression($"__outputs[{index}]"))
        );

        return $"new {ResultTypeName(export)}({members})";
    }

    private static string ResultParameterName(ContractExport export) =>
        export.Outputs.Count() > 1 ? "result" : Camel(export.Outputs.First().Name);

    private static string ResultTypeName(ContractExport export) => $"{MethodName(export)}Result";

    /// <summary>
    /// The generated method name: the contract's own if it gave one, otherwise the predicate name in
    /// .NET casing. This is the equivalent of F#'s <c>[CompiledName]</c>.
    /// </summary>
    private static string MethodName(ContractExport export) => export.ClrName ?? Pascal(export.PredicateName);

    /// <summary>
    /// The backing field for a predicate. It uses the unescaped name: a field already begins with an
    /// underscore, so it can never collide with a keyword, and an <c>@</c> would land in the middle
    /// of the identifier — <c>_@double2</c> does not compile.
    /// </summary>
    private static string Field(ContractExport export) => $"_{LowerFirst(Pascal(export.PredicateName))}{export.Arity}";

    private static string Lower(Determinism determinism) => determinism.ToString().ToLowerInvariant();

    /// <summary>Turns a Prolog identifier such as <c>in_stock</c> into <c>InStock</c>.</summary>
    private static string Pascal(string name)
    {
        var text = new StringBuilder(name.Length);
        bool upper = true;

        foreach (char c in name)
        {
            if (c == '_')
            {
                upper = true;
                continue;
            }

            text.Append(upper ? char.ToUpperInvariant(c) : c);
            upper = false;
        }

        return text.Length == 0 ? "Predicate" : text.ToString();
    }

    /// <summary>A parameter or local name, escaped with <c>@</c> when it collides with a keyword.</summary>
    private static string Camel(string name)
    {
        string camel = LowerFirst(Pascal(name));
        return SyntaxFacts.IsKeyword(camel) ? "@" + camel : camel;
    }

    private static string LowerFirst(string name) => char.ToLowerInvariant(name[0]) + name[1..];
}
